"""
predict.py — GSS Live Inference via MQTT
=========================================
Subscribes to the MQTT broker, receives sensor readings,
runs them through the trained Random Forest, and prints
the classification result with a coloured alert level.

Usage:
  python predict.py
  python predict.py --broker 192.168.1.100 --topic gas_sensors/lab

Requires model/rf_model.pkl, model/scaler.pkl, model/encoder.pkl
(generated by train_random_forest.py)
"""

import argparse
import json
import pickle
import re
import time

import numpy as np
import paho.mqtt.client as mqtt

from preprocess import SENSOR_COLS

MODEL_DIR = "model"

ALERT_COLORS = {
    "Normal":    "\033[92m",   # green
    "Dangerous": "\033[91m",   # red
    "Recovery":  "\033[93m",   # yellow
}
RESET = "\033[0m"


def load_artifacts():
    def load(name):
        with open(f"{MODEL_DIR}/{name}", "rb") as f:
            return pickle.load(f)
    return load("rf_model.pkl"), load("scaler.pkl"), load("encoder.pkl")


def parse_influx_line(line: str) -> dict:
    """
    Parse InfluxDB line protocol:
      gas_sensors,location=lab field1=val,field2=val timestamp
    Returns a dict of {field: float}.
    """
    # Strip measurement+tags and optional timestamp
    fields_part = re.sub(r"^[^\s]+ ", "", line).split(" ")[0]
    result = {}
    for kv in fields_part.split(","):
        if "=" in kv:
            k, v = kv.split("=", 1)
            try:
                result[k.strip()] = float(v.strip())
            except ValueError:
                pass
    return result


def classify(model, scaler, encoder, reading: dict):
    """Extract feature vector and return predicted label."""
    try:
        vec = np.array([[reading.get(col, 0.0) for col in SENSOR_COLS]])
        vec_scaled = scaler.transform(vec)
        pred = model.predict(vec_scaled)[0]
        proba = model.predict_proba(vec_scaled)[0]
        label = encoder.inverse_transform([pred])[0]
        confidence = max(proba) * 100
        return label, confidence
    except Exception as e:
        return "Error", 0.0


def on_message(client, userdata, msg):
    model, scaler, encoder = userdata
    payload = msg.payload.decode("utf-8").strip()
    reading = parse_influx_line(payload)

    if not reading:
        print(f"[!] Could not parse payload: {payload}")
        return

    label, conf = classify(model, scaler, encoder, reading)
    color = ALERT_COLORS.get(label, "")
    ts = time.strftime("%H:%M:%S")

    print(f"[{ts}] {color}▶ {label:<12}{RESET} ({conf:.1f}%) | "
          f"MQ3={reading.get('mq3_v',0):.3f}V "
          f"MQ7={reading.get('mq7_v',0):.3f}V "
          f"Temp={reading.get('temp',0):.1f}°C")


def parse_args():
    p = argparse.ArgumentParser(description="GSS Live Inference")
    p.add_argument("--broker",  default="localhost")
    p.add_argument("--port",    type=int, default=1883)
    p.add_argument("--topic",   default="gas_sensors/lab")
    return p.parse_args()


def main():
    args = parse_args()
    print(f"Loading model artifacts from '{MODEL_DIR}/'...")
    model, scaler, encoder = load_artifacts()
    print(f"Subscribing to {args.broker}:{args.port}/{args.topic}\n")

    client = mqtt.Client(userdata=(model, scaler, encoder))
    client.on_message = on_message
    client.connect(args.broker, args.port, keepalive=60)
    client.subscribe(args.topic)
    client.loop_forever()


if __name__ == "__main__":
    main()
